config/routes.rb
CITS4230Ii::Application.routes.draw do

  resources :users
  resources :images
  resources :sessions, :only => [:new, :create, :destroy]
  resources :friendships

  root :to => 'pages#home'

  match '/mypage', :to => 'users#show'
  match '/mypictures', :to => 'users#pictures'
  match '/pictures/:id', :to => 'users#pictures', :as => :pictures
  match '/register', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/upload', :to => 'images#new'
  match '/user/remove_avatar', :to => 'users#remove_avatar'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  date_of_birth   :date
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
    extend FriendlyId
    friendly_id :name

    attr_accessible :name, :email, :password, :password_confirmation, :avatar

    has_secure_password
    has_many :images, dependent: :destroy
    has_many :friendships
    has_many :friends, :through => :friendships
    has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    has_many :inverse_friends, :through => :inverse_friendships, :source => :user

    has_attached_file :avatar, :styles =>{:thumb => "50x50>"}


    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_USERNAME_REGEX = /^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/
    validates :name, presence: true, uniqueness: true, length: { maximum:20 },  format: { with: VALID_USERNAME_REGEX }
    validates :email, presence: true, uniqueness: { case_sensitive: false },  format: { with: VALID_EMAIL_REGEX }

    before_save { |user| user.email = email.downcase }
    before_save :create_remember_token

    validates :password, presence: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true

    private
    def create_remember_token
        self.remember_token = SecureRandom.urlsafe_base64
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_filter :signed_in_user, only: [:index, :edit, :update]
    before_filter :correct_user,   only: [:edit, :update]


    # GET /users
    # GET /users.json
    def index
        @users = User.paginate(page: params[:page])

        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @users }
        end
    end


    def pictures
        if params[:name]
            @user = User.find_by_name(params[:name])
        else
            if params[:id]
                @user = User.find(params[:id])
            else
                signed_in_user
                @user = current_user
            end
        end

        @images = @user.images
        @groups = @images.all.map {|i| i.group}.uniq

    end

    # GET /users/1
    # GET /users/1.json
    def show

        if params[:name]
            @user = User.find_by_name(params[:name])
        else
            if params[:id]
                @user = User.find(params[:id])
            else
                signed_in_user
                @user = current_user
            end
        end

        # respond_to do |format|
        #     format.html # show.html.erb
        #     format.json { render json: @user }
        # end
    end

    # GET /users/new
    # GET /users/new.json
    def new
        sign_out
        @user = User.new

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @user }
        end
    end

    # GET /users/1/edit
    def edit
        @user = User.find(params[:id])
    end

    # POST /users
    # POST /users.json
    def create
        @user = User.new(params[:user])

        respond_to do |format|
            if @user.save
                sign_in @user
                format.html { redirect_to @user}#, notice: 'User was successfully created.' }
                format.json { render json: @user, status: :created, location: @user }
                flash[:success] = "User Succesfully created!"
            else
                format.html { render action: "new" }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # PUT /users/1
    # PUT /users/1.json
    def update
        @user = User.find(params[:id])

        respond_to do |format|
            if @user.update_attributes(params[:user])
                format.html { redirect_to @user}
                format.json { head :no_content }
                flash[:success] = "Profile updated"
                sign_in @user
            else
                format.html { render action: "edit" }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
        @user = User.find(params[:id])
        @user.destroy

        respond_to do |format|
            format.html { redirect_to users_url }
            format.json { head :no_content }
        end
    end

    def signed_in_user
        unless signed_in?
            store_location
            redirect_to login_url, notice: "Please sign in."
        end
    end
    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_path) unless current_user?(@user)
    end

    def add_friend
        store_location
    end

    def remove_friend
    end

    def remove_avatar
        @user = User.find(params[:id])
        @user.avatar.destroy
        @user.save( :validate => false )
        sign_in @user
        respond_to do |format|
            format.html { redirect_to edit_user_path(@user) }
            format.json { head :no_content }
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper

    # Returns the Gravatar (http://gravatar.com/) for the given user.
    def gravatar_for(user,size=50)
        if has_avatar? user
            image_tag(user.avatar.url(:thumb), alt: user.name, class: "gravatar", width: 50)

        else
            email=user.email.to_s+""

            gravatar_id = Digest::MD5::hexdigest(email.downcase)
            gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
            image_tag(gravatar_url, alt: user.name, class: "gravatar", width: 50)
        end
    end

    def has_avatar? user
        user.avatar_file_name != nil
    end
end

app/views/users/_form_user.html.erb
    <%= form_for(@user) do |f| %>
    <div class="form_settings">
    <%= render 'shared/error_messages' %>


      <p><%= f.label :name%></p>
      <p><%= f.text_field :name, :required => true, :placeholder => "enter username" %></p>

      <p><%= f.label :email %></p>
      <p><%= f.email_field :email, :required => true, :placeholder=> "enter email@example.com"%></p>

      <p><%= f.label :password%></p>
      <p><%= f.password_field :password, :required => true, :placeholder => "enter password (more than 6 characters)", :pattern => '\S{6,}' %></p>

      <p><%= f.label :password_confirmation, "Confirmation" %></p>
      <p><%= f.password_field :password_confirmation, :required => true,
       :placeholder => "confirm password", :oninput => "checkPasswords();" %></p><br/>
      <%if yield(:form_type) ==  'edit' %>
      <hr/><%= gravatar_for @user %>
      <% if has_avatar? @user %>
        <%= link_to "Remove uploaded image (use gravatar)", {:controller => :users,
      :action => 'remove_avatar', :id => @user.id} %>
      <% else %>
      <a href="http://gravatar.com/emails">change gravatar</a>
      <p><%= f.label :avatar, "Or upload image" %></p>
      <p><%= f.file_field :avatar, :accept => "image/*", :placeholder => "select avatar" %></p>
      <% end %>
      <% end %>

      <hr/><br/>

      <p><%= f.submit "Submit", class: "submit" %></p>
    </div>
    <% end %>

app/views/users/_other_user_info.html.erb
<% if friends? @user %>
<%= link_to "Remove Friends", current_user.friendships.find_by_friend_id(@user.id), :method => :delete %>
<%elsif signed_in?%>
<%= link_to "Add Friend", friendships_path(:friend_id => @user.id), :method => :post %>
<%end%>

<h2><%= "#{@user.name}'s friends" %></h2>
<ul>
<% @user.friends.each do |friend| %>
    <li><%= render friend %></li>
<% end %>
</ul>

app/views/users/_user.html.erb
<%= gravatar_for user, size: 50 %>
<%= link_to user.name, user %>
<% if current_user? user %>
( you )
<% elsif !friends? user %>
<%= #link_to "Add Friend", friendships_path(:friend_id => user), :method => :post
%>
<% end %>

app/views/users/_user_friend_info.html.erb
<%= link_to "Edit Profile", edit_user_path(current_user) %>
<h2> Your Friends </h2>
You have <%= pluralize(friend_count(current_user), 'friend') %>
<ul>
<% current_user.friends.each do |friend| %>
<% if friends? friend %>
<br /><li><%= render friend %>
(<%= link_to "remove", current_user.friendships.find_by_friend_id(friend.id), :method => :delete, :confirm => "Are you sure?" %>)
</li>
<% end %>
<% end %>
</ul>

<h2> Your Received Requests </h2>
You have <%= pluralize(received_requests(current_user), 'friend') %> pending
<ul>
<% current_user.inverse_friendships.each do |inverse_friendship| %>
<% unless friends? inverse_friendship.user %>
<br /><li><%= render inverse_friendship.user %>
(<%= link_to "decline", inverse_friendship, :method => :delete %>)
(<%= link_to "accept", friendships_path(:friend_id => inverse_friendship.user.id), :method => :post %>)
</li>
<% end %>
<% end %>
</ul>

<h2> Your Sent Requests </h2>
You have sent <%= pluralize(sent_requests(current_user), 'request') %>
<ul>
<% current_user.friendships.each do |friendship| %>
<% unless friends? friendship.friend %>
<br /><li><%= render friendship.friend %>
(<%= link_to "remove", friendship, :method => :delete, :confirm => "Are you sure?" %>)
</li>
<% end %>
<% end %>
</ul>

app/views/users/edit.html.erb
<% provide(:title, @user.name) %>
<% provide(:form_type, 'edit') %>

  <%= render 'form_user' %>
    <br/> <br/>
    <p><%= link_to "Delete Account", @user, method: :delete,
                                  data: { confirm: "You sure?" } %></p>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
<% @users.each do |user| %>
<li>
    <%= render user %>
</li>
<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<% provide(:form_type, 'new') %>
<h1>Register</h1>

<%= render 'form_user' %>

app/views/users/pictures.html.erb
<% provide(:title, @user.name) %>

<h1>
  <%= gravatar_for @user %>
  <%= link_to @user.name, @user %>
</h1>
<div>user has <%=pluralize(@images.count, 'image')%>, <%= pluralize(@images.where(:private => true).count, 'image is', 'images are') %> private :D</div>


<div id = "imgwrap">
    <% @groups.each do |group| %>
        <hr />
    <div class= "imgblock" id= <%= "#{group}block" %> >
        <h2> <%= group %> <span> -</span></h2>
        <ul class = "imglist">
        <% @images.where(:group => group).each do |image| %>
	    <% if current_user? @user or !image.private or @user.friends.include? current_user %>
		<li>
            <br />

            <h3>Name: <%= image.name %></h3>
	        <p>Uploaded at: <%= image.created_at %></p>

            <% if current_user? @user %>
            <p>Private: <%=image.private %></p>
            <%= link_to 'View Sizes', image %>
            <%= link_to 'Edit', edit_image_path(image) %>
            <%= link_to 'Delete', image, confirm: 'Are you sure?', method: :delete %>
            <% end %>

            <%= link_to image_tag(image.pic.url(:small), :draggable => "true"), '/mypix'+image.pic.url(:large),  class: "lightbox[#{group}]"%>
            </li>
            <hr />
	   <% end %>
        <%end%>
        </ul>
    </div>
    <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1>
  <%= render @user %>
</h1>
<%= link_to "User's Pictures", pictures_path(@user) %>
<%if current_user? @user %>
<%= render 'user_friend_info' %>
<% else %>
<%= render 'other_user_info' %>
<% end %>

</div>