config/routes.rb
CITS4230Ii::Application.routes.draw do

  resources :users
  resources :images
  resources :sessions, :only => [:new, :create, :destroy]
  resources :friendships

  root :to => 'pages#home'

  match '/mypage', :to => 'users#show'
  match '/mypictures', :to => 'users#pictures'
  match '/pictures/:id', :to => 'users#pictures', :as => :pictures
  match '/register', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/upload', :to => 'images#new'
  match '/user/remove_avatar', :to => 'users#remove_avatar'

end

app/views/pages/home.html.erb
<h1>Welcome <%= @current_user.name if signed_in?%> </h1>

<div class= "imgblock" id= "recentblock"> >
        <h2> Recent Images <span> -</span></h2>
        <ul class = "imglist">
        <% @images.each do |image| %>
            <li>
	       <% if !image.private %>
	       <%= link_to image_tag(image.pic.url(:small), :draggable => "true"), image.pic.url(:large),  class: "lightbox[recent]"%>
           uploaded by <%= link_to image.user.name, user_path(image.user) %> <%= time_ago_in_words(image.created_at)%> ago
	       <% end%>
	       </li><br/>
        <%end%>
        </ul>
    </div>

    <div id="checkOnline">
        <h2>Website is available at </h2>
        <ul>
            <li> http://mypix.herokuapps.com (stable, fully functional except images are deleted after some time) </li>
            <li> http://cits4230c.csse.uwa.edu.au/mypix (unstable) </li>
        </ul>


</div>

app/views/pages/mypage.html.erb
<% provide(:title, 'My Page') %>

<% if signed_in? %>
    <p> You are logged in as :<%= @current_user.name %></p>
<%else%>
     <p>You aren't logged in, <%= link_to "Click here to login!", login_path %></p>
<%end%>

app/views/pages/upload.html.erb
<% provide(:title, 'Upload') %>
<h1>Pages#upload</h1>
<p>Find me in app/views/pages/upload.html.erb</p>