config/routes.rb
CITS4230Ii::Application.routes.draw do

  resources :users
  resources :images
  resources :sessions, :only => [:new, :create, :destroy]
  resources :friendships

  root :to => 'pages#home'

  match '/mypage', :to => 'users#show'
  match '/mypictures', :to => 'users#pictures'
  match '/pictures/:id', :to => 'users#pictures', :as => :pictures
  match '/register', :to => 'users#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/upload', :to => 'images#new'
  match '/user/remove_avatar', :to => 'users#remove_avatar'

end

app/views/layouts/_footer.html.erb
        <div id="content_footer"></div>
        <footer id="footer">
            <p>
                Copyright © Felix Dumit - 21203542 | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">design from HTML5webtemplates.co.uk</a>
            </p>
        </footer>

app/views/layouts/_header.html.erb
        <header id="header">
            <div id="logo">
                <div id="logo_text">
                    <!-- class="logo_colour", allows you to change the colour of the text -->
                    <h1>
                        <a href="/">My<span class="logo_colour">Pix</span></a>
                    </h1>
                    <h2>
                        Image Uploading and Sharing
                    </h2>
                </div>
            </div>
            <nav id="menubar">
                <ul id="menu">
                    <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
                    <li class=<%= yield(:title) == '' ? "selected" : "" %>>
                        <%= link_to 'Home', root_path %>
                    </li>
                    <li class=<%= yield(:title) == getName(@user) ? "selected" : "" %>>
                        <%= link_to 'My Page', mypage_path %>
                    </li>
                    <li class=<%= yield(:title) == 'Upload' ? "selected" : "" %>>
                        <%= link_to 'Upload', upload_path %>
                    </li>
                    <li class=<%= yield(:title) == 'All users' ? "selected" : "" %>>
                        <%= link_to "Users", users_path %>
                    </li>
                    <li class=<%= yield(:title) == 'Register' ? "selected" : "" %>>
                        <%= link_to 'Register', register_path %>
                    </li>
                </ul>
            </nav>
        </header>

app/views/layouts/_sidebar.html.erb
        <div id="sidebar_container">
            <div class="sidebar">
                <div class="sidebar_top"></div>
                <div class="sidebar_item">
                    <h3>
                        My Links
                    </h3>
                    <ul>
                        <% if signed_in? %>
                         <li>
                             <%= link_to "My Account",mypage_path %>
                        </li>
                        <li>
                             <%= link_to "Edit Profile",edit_user_path(current_user) %>
                        </li>
                        <li>
                             <%= link_to "My Pictures", mypictures_path %>
                        </li>
                        <li>
                             <%= link_to "Upload", upload_path %>
                        </li>
                        <li>
                             <%= link_to "Logout(#{@current_user.name})", logout_path %>
                        </li>
                        <% else %>
                        <li>
                           <%= link_to "Login", login_path %>
                        </li>
                        <li>
                            <%= link_to "Register", register_path %>
                        </li>
                        <% end %>


                    </ul>
                </div>
                <div class="sidebar_base"></div>
            </div>
            <div class="sidebar">
                <div class="sidebar_top"></div>
                <div class="sidebar_item">
                    <h3>
                        Search
                    </h3>
                    <form method="post" action="#" id="search_form">
                        <p>
                            <input class="search" type="text" name="search_field" placeholder="Enter keywords....."> <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="/mypix/assets/search.png" alt="Search" title="Search">
                        </p>
                    </form>
                </div>
                <div class="sidebar_base"></div>
            </div>
            <div class="sidebar">
                <div class="sidebar_top"></div>
                <div class="sidebar_item">
                    <!-- insert your sidebar items here -->
                    <h3>
                        Latest News
                    </h3>
                    <h4>
                        CITS4230 - Project 1
                    </h4>
                    <h5>
                        September 14th, 2012
                    </h5>
                    <p>
                        First part of project released,<br>
                        <a href="references.html">see references</a>
                    </p>
                </div>
                <div class="sidebar_base"></div>
            </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>

<head>
 <title><%= full_title(yield(:title)) %></title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<div>
<body id = "main">
    <div>
        <%= render 'layouts/header' %>
       <div id="content_header"></div>
        <section id="site_content">
               <% flash.each do |key, value| %>
                  <div class="alert alert-<%= key %>"><%= value %></div>
               <% end %>

                <%= render 'layouts/sidebar' %>
                <div id="content">
                    <!-- insert the page content here -->
                    <%= yield %>
                </div>
        </section>
        <%= render 'layouts/footer' %>
    </div>
</body>
<script> initImgs(); </script>
<div>
</html>